### ISSUE TITLE
Use-Cases erstellen

### ISSUE THREAD

**Issue by 54nd20** [night28/HSR_SA#14]
Bis am Donnerstag dem 08.03.2018 Notizen machen.

**Comment by night28** [comment]
Use cases Bereiche (circa 10 Use cases generieren) 

- Definierung von Benutzer- und Geräteprofile, um basierend auf Geschäftsanforderungen die Zugriffsrechte und Netzwerksegmentierung zu verwalten und so das Netzwerk sicher zu halten.

- Durch APIs, Erstellung von Wochentlichen Reports über Campus Netzwerk-Status in einem E-Mail und in einem Slack Message.

**Comment by night28** [comment]
Use cases Bereiche (circa 10 Use cases generieren) 

- Definierung von Benutzer- und Geräteprofile, um basierend auf Geschäftsanforderungen die Zugriffsrechte und Netzwerksegmentierung zu verwalten und so das Netzwerk sicher zu halten.

- Durch APIs, Erstellung von Wochentlichen Reports über Campus Netzwerk-Status in einem E-Mail und in einem Slack Message.

**Comment by night28** [comment]
- Sicherheit und Segmentierung
- Überwachung und Fehlerbehebung 
- Benutzermobilität
- Gastzugang
- IoT-Integration
- Cloud-Datacenter-Integration
- Branchenintegration

**Comment by 54nd20** [comment]
* Inbetriebnahme neuer Switch
* Hardwareersatz
* Backup /Restore DNA Center
* Backup / Restore ISE
* Troubleshooting
* Kombination mit traditionellen Netzwerken
* IPAM

**Comment by 54nd20** [comment]
Was passiert bei manueller Konfiguration auf einem Switch?

**Comment by 54nd20** [comment]
Folgende Use Cases sind in Doku:
* Definiertung von Benutzer und Geräteprofilen
* Gastzugang
* Backup / Restore DNA Center
* Reporting
* Hardware Ersatz
* Benutzermobilität
