### ISSUE TITLE
Meilensteine anpassen

### ISSUE THREAD

**Issue by 54nd20** [night28/HSR_SA#35]

**Comment by 54nd20** [comment]
Anpassung bei Risiken dokumentieren

**Comment by night28** [comment]
Lieferverzögerung Hardware wurde als eingetretenes Risiko dokumentiert und die zeitliche Planung angepasst.

**Comment by night28** [comment]
Zeitliche Planung erneut angepasst aufgrund weiterer Lieferverzögerung
