### ISSUE TITLE
Einarbeitung in eine neue Aufgabenstellung

### ISSUE THREAD

**Issue by night28** [night28/HSR_SA#7]

**Comment by night28** [comment]
https://www.cisco.com/c/en/us/solutions/enterprise-networks/software-defined-access/index.html
In dieser Webseite können sie lesen warum Software Defined Networks ein wichtiges Thema der Zukunkt ist. 
 
Bitte auch dieses Video bis mindestens Minute 11 anschauen. Dort wird die Grundlagen eines Software Defined Networks erklärt.
https://drive.google.com/file/d/1EEa9rdTJwo1WwL0Eyx26pTmh4NzMGzTg/view?usp=sharing

**Comment by night28** [comment]
Die Videos könnt ihr auf https://digital-learning.cisco.com/course/58487 anschauen.  Es geht um die Schnittstelle zwischen DNA-Center und ISE die ihr voraussichtlich bauen werdet.

Module 2, Lesson 2 Part 1 & 2

**Comment by p1albrec** [comment]
This issue was moved to night28/HSR_SA_FS2018#6
